Update GitHub actions
Ed-Fi-Alliance-OSS/Ed-Fi-Actions pull request #72
Opened 2024-03-05 16:12 UTC by stephenfuqua

2024-03-06 20:51 UTC, andonyns commented on .github/workflows/after-pullrequest-powershell.yml
> +        uses: dorny/test-reporter@eaa763f6ffc21c7a37837f56cd5f9737f27fc6c8 # v1.8.0
This happens when we upgrade upload-artifacts

2024-03-06 21:45 UTC, stephenfuqua commented on .github/workflows/after-pullrequest-powershell.yml
> +        uses: dorny/test-reporter@eaa763f6ffc21c7a37837f56cd5f9737f27fc6c8 # v1.8.0
I'm testing out a fork of dorny/test-reporter now.

2024-03-07 19:25 UTC, andonyns requested changes

2024-03-07 19:25 UTC, andonyns commented on .github/workflows/after-pullrequest-bidi.yml
> +    if: github.event.workflow_run.conclusion != 'skipped'
I like this approach

2024-03-07 19:31 UTC, stephenfuqua commented on bidi-scanner/action.yml
> +  using: node20
`node18` does not exist in GitHub, in this context.

2024-03-07 19:32 UTC, stephenfuqua commented on action-allowedlist/README.md
> +        uses: actions/26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
```suggestion
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
```

2024-03-07 19:33 UTC, stephenfuqua commented on bidi-scanner/github/package.json
> +    "node": ">=18.0.0"
Node 18 _does_ exist as an option when running custom code. You just can't choose `node18` in `action.yml`.

2024-03-07 19:45 UTC, andonyns approved these changes

2024-03-07 19:45 UTC, merged